# Site settings
baseurl = "http://willjharmer.github.io/"
languageCode = "en-uk"
title = "William Harmer Blog"
theme = "hugo-cactus-theme"
canonifyurls = true
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "blog-willjharmer"

[params]
	name = "William Harmer"
	description = "A technical blog about my work and interests"
	bio = "Data Scientist - Developer - Creative"
	# Enter optionally your twitter account
	twitter = "harmer_will"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "A type.II Data Scientist with a software engineering background working with the Python ecosystem "
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/harmer_will"
    facebook = "https://www.facebook.com/william.harmer.7"
    github   = "https://www.github.com/willjharmer"
